export const 
  TYPE_INDEX = 0,
  NAME_INDEX = 1,
  REGION_INDEX = 2,
  Q1_INDEX = 3,
  Q2_INDEX = 4,
  Q3_INDEX = 5,
  Q4_INDEX = 6,
  MAAL_INDEX = 7,
  TOTAL_INDEX = 9,
  MAJLIS_SIZE_INDEX = 10,
  RANK_INDEX = 11;
